### ISSUE TITLE
How do I get at the Header?

### ISSUE THREAD

**Issue by makoConstruct** [vadixidav/header-vec#1]
Once I have `let v = HeaderVec::new(h)`, how do I get get a reference to h from v?

**Comment by vadixidav** [comment]
The [`HeaderVec` implements Deref](https://docs.rs/header-vec/0.1.0/header_vec/struct.HeaderVec.html#impl-Deref). This means that you can call methods that `h` contains directly on the `HeaderVec`, and you can also access its members directly.
